### ISSUE TITLE
Use LoopVectorization.@turbo on unrolled loops

### ISSUE THREAD

**Issue by ChrisRackauckas** [vboussange/HighDimPDE.jl#6]
https://github.com/vboussange/HighDimPDE.jl/blob/main/src/reflect.jl#L12-L36

This should be using `LoopVectorization.@turbo`, or `LoopVectorization.@tturbo`.

**Comment by vboussange** [comment]
This seems not trivial as `LoopVectorization.@turbo` does not support `if` statements:
```Julia
@turbo for i in 1:10
       if i > 5
          println(i)
       end
end
```
returns
```
ERROR: LoadError: Don't know how to handle expression.
if i > 5
    #= REPL[6]:3 =#
    println(i)
end
```

**Comment by ChrisRackauckas** [comment]
Oh yes, missed that, and it's hard to hoist out.
